# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "922282a3229a4b63a8241b2032e1f9d3"
name = "app-acciona"
handle = "app-acciona"
application_url = "https://declaration-mambo-alternatively-thinking.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://declaration-mambo-alternatively-thinking.trycloudflare.com/auth/callback",
  "https://declaration-mambo-alternatively-thinking.trycloudflare.com/auth/shopify/callback",
  "https://declaration-mambo-alternatively-thinking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/create"

[pos]
embedded = false

[build]
dev_store_url = "fik-checkoutext-preview.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
